/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital_management;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class AddNewPatientRecord extends javax.swing.JFrame {

    /**
     * Creates new form AddNewPatientRecord
     */
    public AddNewPatientRecord() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Patient_ID = new javax.swing.JTextField();
        Patient_Name = new javax.swing.JTextField();
        Contact_Number = new javax.swing.JTextField();
        Age = new javax.swing.JTextField();
        Gender = new javax.swing.JComboBox<>();
        Blood_Group = new javax.swing.JTextField();
        Address = new javax.swing.JTextField();
        Date = new javax.swing.JTextField();
        disease = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        weight = new javax.swing.JTextField();
        height = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(380, 150));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(780, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_management/Close.png"))); // NOI18N
        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 470, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Patient's Name:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 120, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Patient ID:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 90, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Contact Number:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 130, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Age:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 40, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Gender:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 60, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Blood Group:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 100, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Address:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 70, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Any Major Diseases Suffered Before:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Date Of Admission:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 140, -1));

        Patient_ID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Patient_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Patient_IDActionPerformed(evt);
            }
        });
        getContentPane().add(Patient_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 199, -1));

        Patient_Name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(Patient_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 199, -1));

        Contact_Number.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(Contact_Number, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 199, -1));

        Age.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(Age, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 199, -1));

        Gender.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Others" }));
        getContentPane().add(Gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 199, -1));

        Blood_Group.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(Blood_Group, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 199, -1));

        Address.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, 199, -1));

        Date.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, 199, -1));

        disease.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(disease, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, 450, -1));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 520));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_management/save-icon--1.png"))); // NOI18N
        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 470, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Weight:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Height:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Co-Morbidities:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        weight.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        weight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightActionPerformed(evt);
            }
        });
        getContentPane().add(weight, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 200, -1));

        height.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(height, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, 200, -1));

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox1.setText("Yes");
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_management/add new patient background.jpg"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 510));

        jLabel15.setText("jLabel15");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Patient_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Patient_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Patient_IDActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        
        String patient_ID=(Patient_ID.getText());
        String patient_Name=Patient_Name.getText();
        String Contact_Number=(this.Contact_Number.getText());
        String Weight=weight.getText();
        String Height=height.getText();
        String Age=(this.Age.getText());
        String Gender=(String) this.Gender.getSelectedItem();
        String Blood_Group=this.Blood_Group.getText();
        String Address=this.Address.getText();
        String Date=this.Date.getText();
        String Disease=disease.getText();
        String Co_morbidities;
        if(jCheckBox1.isSelected())
            Co_morbidities="Yes";
        else
            Co_morbidities="No";
                    
        
        /*System.out.println(patient_ID+" "+
                patient_Name+" "+
                Contact_Number+" "+
                Age+" "+
                Gender+" "+
                Blood_Group+" "+
                Address+" "+
                Date+" "+
                Disease);*/
        //create sql query to put data into database
        if(patient_ID.equals("")||
                Weight.equals("")||
                Height.equals("")||
                Co_morbidities.equals("")||
                patient_Name.equals("")||
                Contact_Number.equals("")||
                 Age.equals("")||
                 Gender.equals("")||
                Blood_Group.equals("")||
                Address.equals("")||
                Date.equals("")||
                Disease.equals("")){
            JOptionPane.showMessageDialog(null,"Kindly Fill Out All Necessary Info!");
            
        }
        else{
            try {
                Connection conn= Get_Connection.connect_to_database();
                Statement st=conn.createStatement();
                String query="insert into patient values('"+patient_ID+"','"+patient_Name+"','"+Contact_Number+"','"+Age+"','"+Gender+"','"+Blood_Group+"','"+Address+"','"+Date+"','"+Disease+"','"+Weight+"','"+Height+"','"+Co_morbidities+"' )";
                st.executeUpdate(query);
                JOptionPane.showMessageDialog(null,"Patient Detail Added Successfully!!");
                setVisible(false);
                new AddNewPatientRecord().setVisible(true);
                
            } catch (Exception ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null,"Error!");
            }
             
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void weightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weightActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewPatientRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewPatientRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewPatientRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewPatientRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddNewPatientRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Address;
    private javax.swing.JTextField Age;
    private javax.swing.JTextField Blood_Group;
    private javax.swing.JTextField Contact_Number;
    private javax.swing.JTextField Date;
    private javax.swing.JComboBox<String> Gender;
    private javax.swing.JTextField Patient_ID;
    private javax.swing.JTextField Patient_Name;
    private javax.swing.JTextField disease;
    private javax.swing.JTextField height;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField weight;
    // End of variables declaration//GEN-END:variables
}
